import React, { useState } from 'react';
import { Download, FileText, Table, Printer, Mail, Share2 } from 'lucide-react';
import jsPDF from 'jspdf';

interface ExportOptionsProps {
  measurements: any;
  progressData?: any[];
  recommendations?: any[];
}

const ExportOptions: React.FC<ExportOptionsProps> = ({ 
  measurements, 
  progressData = [], 
  recommendations = [] 
}) => {
  const [isExporting, setIsExporting] = useState(false);
  const [exportFormat, setExportFormat] = useState<'pdf' | 'csv' | 'json'>('pdf');

  const generatePDFReport = () => {
    setIsExporting(true);
    
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.width;
      const margin = 20;
      let yPosition = margin;

      // Header
      doc.setFontSize(24);
      doc.setTextColor(20, 184, 166); // Teal color
      doc.text('BodyFit AI Measurement Report', margin, yPosition);
      yPosition += 15;

      // Date
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition);
      yPosition += 20;

      // Measurements Section
      doc.setFontSize(18);
      doc.setTextColor(0, 0, 0);
      doc.text('Body Measurements', margin, yPosition);
      yPosition += 10;

      doc.setFontSize(12);
      const measurementEntries = Object.entries(measurements);
      measurementEntries.forEach(([key, value]) => {
        const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
        doc.text(`${label}: ${value}`, margin, yPosition);
        yPosition += 8;
      });

      yPosition += 15;

      // Size Recommendations Section
      if (recommendations.length > 0) {
        doc.setFontSize(18);
        doc.text('Size Recommendations', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(12);
        recommendations.slice(0, 5).forEach((item) => {
          doc.text(`${item.name} (${item.brand}): Size ${item.recommendedSize}`, margin, yPosition);
          yPosition += 8;
        });
        yPosition += 15;
      }

      // Progress Section
      if (progressData.length > 0) {
        doc.setFontSize(18);
        doc.text('Progress History', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(12);
        progressData.slice(0, 5).forEach((record) => {
          doc.text(`${record.date}: Waist ${record.measurements.waist}cm, Chest ${record.measurements.chest}cm`, margin, yPosition);
          yPosition += 8;
        });
      }

      // Footer
      const footerY = doc.internal.pageSize.height - 20;
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by BodyFit AI - Precision Body Measurements', margin, footerY);
      doc.text('Visit: https://bodyfit-ai.com', pageWidth - margin - 50, footerY);

      // Save the PDF
      doc.save('bodyfit-ai-measurements.pdf');
    } catch (error) {
      console.error('PDF generation error:', error);
    } finally {
      setIsExporting(false);
    }
  };

  const generateCSVReport = () => {
    setIsExporting(true);
    
    try {
      let csvContent = "data:text/csv;charset=utf-8,";
      
      // Measurements CSV
      csvContent += "Measurement Type,Value\n";
      Object.entries(measurements).forEach(([key, value]) => {
        const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
        csvContent += `${label},${value}\n`;
      });
      
      csvContent += "\n";
      
      // Progress Data CSV
      if (progressData.length > 0) {
        csvContent += "Date,Shoulder Width,Chest,Waist,Hips,Arm Length,Leg Length,Inseam,Neck,Weight,Notes\n";
        progressData.forEach(record => {
          csvContent += `${record.date},${record.measurements.shoulder_width},${record.measurements.chest},${record.measurements.waist},${record.measurements.hips},${record.measurements.arm_length},${record.measurements.leg_length},${record.measurements.inseam},${record.measurements.neck},${record.weight || ''},${record.notes || ''}\n`;
        });
      }

      const encodedUri = encodeURI(csvContent);
      const link = document.createElement("a");
      link.setAttribute("href", encodedUri);
      link.setAttribute("download", "bodyfit-ai-data.csv");
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('CSV generation error:', error);
    } finally {
      setIsExporting(false);
    }
  };

  const generateJSONReport = () => {
    setIsExporting(true);
    
    try {
      const reportData = {
        generatedAt: new Date().toISOString(),
        measurements,
        progressData,
        recommendations: recommendations.slice(0, 10),
        metadata: {
          version: "1.0",
          source: "BodyFit AI",
          format: "JSON"
        }
      };

      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(reportData, null, 2));
      const link = document.createElement("a");
      link.setAttribute("href", dataStr);
      link.setAttribute("download", "bodyfit-ai-data.json");
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error) {
      console.error('JSON generation error:', error);
    } finally {
      setIsExporting(false);
    }
  };

  const handleExport = () => {
    switch (exportFormat) {
      case 'pdf':
        generatePDFReport();
        break;
      case 'csv':
        generateCSVReport();
        break;
      case 'json':
        generateJSONReport();
        break;
    }
  };

  const shareResults = async () => {
    const shareData = {
      title: 'My BodyFit AI Measurements',
      text: `Check out my body measurements from BodyFit AI:\n\nWaist: ${measurements.waist}\nChest: ${measurements.chest}\nHips: ${measurements.hips}`,
      url: window.location.href
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      // Fallback to clipboard
      navigator.clipboard.writeText(shareData.text + '\n\n' + shareData.url);
      alert('Results copied to clipboard!');
    }
  };

  const printResults = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>BodyFit AI Measurements</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .header { color: #14b8a6; font-size: 24px; font-weight: bold; margin-bottom: 20px; }
            .section { margin-bottom: 30px; }
            .section h3 { color: #374151; border-bottom: 2px solid #e5e7eb; padding-bottom: 5px; }
            .measurement { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f3f4f6; }
            .measurement:last-child { border-bottom: none; }
            .label { font-weight: 500; }
            .value { color: #14b8a6; font-weight: bold; }
            .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">BodyFit AI Measurement Report</div>
          <p>Generated on: ${new Date().toLocaleDateString()}</p>
          
          <div class="section">
            <h3>Body Measurements</h3>
            ${Object.entries(measurements).map(([key, value]) => {
              const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
              return `<div class="measurement"><span class="label">${label}</span><span class="value">${value}</span></div>`;
            }).join('')}
          </div>

          ${recommendations.length > 0 ? `
            <div class="section">
              <h3>Size Recommendations</h3>
              ${recommendations.slice(0, 5).map(item => 
                `<div class="measurement"><span class="label">${item.name} (${item.brand})</span><span class="value">Size ${item.recommendedSize}</span></div>`
              ).join('')}
            </div>
          ` : ''}

          <div class="footer">
            Generated by BodyFit AI - Precision Body Measurements<br>
            Visit: https://bodyfit-ai.com
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  const sendEmail = () => {
    const subject = encodeURIComponent('My BodyFit AI Measurements');
    const body = encodeURIComponent(`
Here are my body measurements from BodyFit AI:

${Object.entries(measurements).map(([key, value]) => {
  const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  return `${label}: ${value}`;
}).join('\n')}

Generated on: ${new Date().toLocaleDateString()}

Visit BodyFit AI: https://bodyfit-ai.com
    `);

    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  return (
    <div className="bg-white rounded-2xl shadow-lg p-8">
      <div className="flex items-center space-x-3 mb-6">
        <Download className="w-8 h-8 text-teal-600" />
        <h3 className="text-2xl font-bold text-gray-900">Export & Share</h3>
      </div>

      {/* Export Format Selection */}
      <div className="mb-6">
        <label className="block text-sm font-medium text-gray-700 mb-3">Export Format:</label>
        <div className="flex space-x-4">
          {[
            { id: 'pdf', name: 'PDF Report', icon: FileText, description: 'Professional report with charts' },
            { id: 'csv', name: 'CSV Data', icon: Table, description: 'Spreadsheet compatible format' },
            { id: 'json', name: 'JSON Data', icon: FileText, description: 'Raw data for developers' }
          ].map((format) => {
            const Icon = format.icon;
            return (
              <button
                key={format.id}
                onClick={() => setExportFormat(format.id as any)}
                className={`flex-1 p-4 rounded-lg border-2 transition-all ${
                  exportFormat === format.id
                    ? 'border-teal-500 bg-teal-50'
                    : 'border-gray-200 hover:border-gray-300'
                }`}
              >
                <Icon className={`w-6 h-6 mx-auto mb-2 ${
                  exportFormat === format.id ? 'text-teal-600' : 'text-gray-400'
                }`} />
                <div className="text-sm font-medium text-gray-900">{format.name}</div>
                <div className="text-xs text-gray-500 mt-1">{format.description}</div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Export Button */}
      <div className="mb-8">
        <button
          onClick={handleExport}
          disabled={isExporting}
          className="w-full flex items-center justify-center space-x-2 px-6 py-3 bg-teal-500 text-white rounded-lg hover:bg-teal-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isExporting ? (
            <>
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
              <span>Generating {exportFormat.toUpperCase()}...</span>
            </>
          ) : (
            <>
              <Download className="w-5 h-5" />
              <span>Download {exportFormat.toUpperCase()} Report</span>
            </>
          )}
        </button>
      </div>

      {/* Quick Actions */}
      <div className="border-t border-gray-200 pt-6">
        <h4 className="text-lg font-semibold text-gray-900 mb-4">Quick Actions</h4>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <button
            onClick={printResults}
            className="flex flex-col items-center space-y-2 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <Printer className="w-6 h-6 text-gray-600" />
            <span className="text-sm font-medium text-gray-700">Print</span>
          </button>

          <button
            onClick={sendEmail}
            className="flex flex-col items-center space-y-2 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <Mail className="w-6 h-6 text-gray-600" />
            <span className="text-sm font-medium text-gray-700">Email</span>
          </button>

          <button
            onClick={shareResults}
            className="flex flex-col items-center space-y-2 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <Share2 className="w-6 h-6 text-gray-600" />
            <span className="text-sm font-medium text-gray-700">Share</span>
          </button>

          <button
            onClick={() => navigator.clipboard.writeText(JSON.stringify(measurements, null, 2))}
            className="flex flex-col items-center space-y-2 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <FileText className="w-6 h-6 text-gray-600" />
            <span className="text-sm font-medium text-gray-700">Copy Data</span>
          </button>
        </div>
      </div>

      {/* Export History */}
      <div className="mt-8 bg-gray-50 rounded-lg p-4">
        <h5 className="font-medium text-gray-800 mb-2">Export Tips</h5>
        <ul className="text-sm text-gray-600 space-y-1">
          <li>• PDF reports include charts and professional formatting</li>
          <li>• CSV files can be opened in Excel or Google Sheets</li>
          <li>• JSON format is perfect for importing into other applications</li>
          <li>• All exports include your measurement history when available</li>
        </ul>
      </div>
    </div>
  );
};

export default ExportOptions;