const mongoose = require('mongoose');

const measurementSchema = new mongoose.Schema(
  {
    // Unique identifier for the capture session (UUID generated by API gateway)
    session_id: {
      type    : String,
      required: true,
      index   : true,
    },

    // Optional link to a registered user — null for anonymous sessions
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref : 'User',
      default: null,
    },

    // UTC timestamp of when the measurement was completed
    timestamp: {
      type   : Date,
      default: Date.now,
      index  : true,
    },

    // All body measurements key→value (values include unit, e.g. "94.5 cm")
    measurements: {
      shoulder_width: String,
      chest         : String,
      waist         : String,
      hips          : String,
      arm_length    : String,
      leg_length    : String,
      inseam        : String,
      neck          : String,
    },

    // How the image scale was determined
    calibration_method: {
      type: String,
      enum: ['user_height_anchor', 'reference_object', 'unknown'],
      default: 'unknown',
    },

    // Calibration input details (value in cm or pixel-width of object)
    calibration: {
      type : { type: String },          // 'height' | 'reference'
      value: Number,
      unit : { type: String, default: 'cm' },
    },

    // Model confidence score 0.0–1.0 returned by Python microservice
    confidence: {
      type: Number,
      min : 0,
      max : 1,
    },

    // Free-text notes from the user (optional)
    notes: {
      type: String,
      maxlength: 500,
    },
  },
  { timestamps: true }    // adds createdAt + updatedAt automatically
);

module.exports = mongoose.model('Measurement', measurementSchema);
